dange again error here

diff --git a/bin/.local/scripts/nvim_install b/bin/.local/scripts/nvim_install
--- a/bin/.local/scripts/nvim_install
+++ b/bin/.local/scripts/nvim_install
@@ -45,19 +45,34 @@ echo -e "${BLUE}Info:${NC} Installing packages..."
 
 pacman -S --noconfirm "${packages[@]}"
 
-cd "$HOME" || echo -e "${RED}Error:${NC}Failed to navigate to home directory.\n${BLUE}Info:${NC}aborting...\n" && sleep 2 && return
+cd "$HOME" || {
+    echo -e "${RED}Error:${NC} Failed to navigate to home directory."
+    echo -e "${BLUE}Info:${NC} Aborting...\n"
+    sleep 2
+    exit 1
+}
 
 echo -e "${BLUE}Cloning:${NC} The tmux plugin manager that you gonna use ..." && sleep 2
 git clone https://github.com/tmux-plugins/tpm "$HOME/.tmux/plugins/tpm"
 
 # Clone dotfiles repository
-cd echo -e "${RED} Error:${NC} Failed to navigate to home directory.\n${BLUE}Info:${NC}aborting...\n" && sleep 2 && return
+cd "$HOME" || {
+    echo -e "${RED}Error:${NC} Failed to navigate to home directory."
+    echo -e "${BLUE}Info:${NC} Aborting...\n"
+    sleep 2
+    exit 1
+}
 
 echo -e "${BLUE}Cloning:${NC} Dotfiles form main branch..."
 git clone --depth=1 -b main https://github.com/SantoshShrestha11/dotfiles.git "$HOME/dotfiles/"
 
 # Stow the dotfiles
-cd "$HOME/dotfiles" || echo -e "${BLUE}Error:${NC} Failed to navigate to dotfiles directory.\n${BLUE}Info:${NC}aborting...\n" && sleep 2 && return
+cd "$HOME" || {
+    echo -e "${RED}Error:${NC} Failed to navigate to home directory."
+    echo -e "${BLUE}Info:${NC} Aborting...\n"
+    sleep 2
+    exit 1
+}
 echo -e "Stowing dotfiles..."
 stow nvim tmux fastfetch
 
