the final thing

diff --git a/bin/.local/scripts/nvim_install_for_docker_arch b/bin/.local/scripts/nvim_install_for_docker_arch
--- a/bin/.local/scripts/nvim_install_for_docker_arch
+++ b/bin/.local/scripts/nvim_install_for_docker_arch
@@ -76,6 +76,13 @@ cd "/root/dotfiles" || {
 echo -e "Stowing dotfiles..."
 stow nvim tmux fastfetch
 
+cd "/root" || {
+    echo -e "${RED}Error:${NC} Failed to navigate to /root directory."
+    echo -e "${BLUE}Info:${NC} Aborting...\n"
+    sleep 2
+    exit 1
+}
+
 # This package (neovim on npm) is a Node.js client for Neovim’s RPC API.
 #It allows Node.js applications (like Neovim plugins) to send commands and interact with Neovim.
 npm install -g neovim
